services:


  monolith:
    build: ./monolith
    container_name: monolith
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
      - kafka
      - payment-service
      - billing-service
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/ecommerce
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BROKER: kafka:9092
      KAFKA_PAYMENT_TOPIC: ${KAFKA_PAYMENT_TOPIC}
    networks:
      - my-network

  # -- MongoDB --
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network

  # -- Redis --
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  # -- Zookeeper --
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - my-network

  # -- Kafka --
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "payment-completed:1:1"
    depends_on:
      - zookeeper
    networks:
      - my-network

  # -- Payment Service --
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "4000:4000"
    depends_on:
      - kafka
    environment:
      PORT: ${PAYMENT_SERVICE_PORT}
      KAFKA_BROKER: kafka:9092
      KAFKA_PAYMENT_TOPIC: ${KAFKA_PAYMENT_TOPIC}
    networks:
      - my-network

  # -- Billing Service --
  billing-service:
    build: ./billing-service
    container_name: billing-service
    ports:
      - "5000:5000"
    depends_on:
      - kafka
    environment:
      PORT: ${BILLING_SERVICE_PORT}
      KAFKA_BROKER: kafka:9092
      KAFKA_PAYMENT_TOPIC: ${KAFKA_PAYMENT_TOPIC}
    networks:
      - my-network

  # -- React Frontend --
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:3000"
    depends_on:
      - monolith
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
